### ISSUE TITLE
Missing TypeScript declaration file for @smarttools/eslint-plugin-rxjs

### ISSUE THREAD

**Issue by Oussemasahbeni** [DaveMBush/eslint-plugin-rxjs#26]
I am using the @smarttools/eslint-plugin-rxjs plugin in my project, and it works fine. However, I am encountering a TypeScript warning because there is no type declaration file for this module. The warning message is as follows:

`Could not find a declaration file for module '@smarttools/eslint-plugin-rxjs'. 'c:/Users/sahba/OneDrive/Desktop/inspark/onesaha/onesaha-frontend/node_modules/@smarttools/eslint-plugin-rxjs/index.cjs' implicitly has an 'any' type.
  Try npm i --save-dev @types/smarttools__eslint-plugin-rxjs if it exists or add a new declaration (.d.ts) file containing `declare module '@smarttools/eslint-plugin-rxjs';`ts(7016)
  
 Could you please add a TypeScript declaration file for the @smarttools/eslint-plugin-rxjs module or provide guidance on how to resolve this issue?`

**Comment by DaveMBush** [comment]
There is nothing in eslint, which uses js or json config files, that would require type files.

It sounds to me like you need to exclude your eslint config file from your typescript compilation.

**Comment by Oussemasahbeni** [comment]
im using a eslint.config.mjs file so i can use import instead of require

**Comment by DaveMBush** [comment]
Even then, it is essentially a javascript file, and not typescript.

Are you getting this error running eslint or when you build your project?

**Comment by Oussemasahbeni** [comment]
![image](https://github.com/user-attachments/assets/c2d702ea-af7d-4d31-8fd3-86478557a535)
In my ide here

**Comment by DaveMBush** [comment]
You have several options:

1) if tsconfig.json or your editor is configured to check JavaScript files (via allowJs or checkJs), TypeScript type checking will apply to .mjs and .js files.  You might consider turning this off.
2) Create a Module Declaration: If no type definitions are available, declare the module manually. Add a global.d.ts file in your project with the following:

``` typescript
declare module '@smarttools/eslint-plugin-rxjs';
```
this tells typescript to treat the module as `any`
3) Add tsignore to the line above like you've already done for `@eslint/js`
4) Exclude this specific file from typechecking in tsconfig.json so it doesn't get typechecked.

**Comment by Oussemasahbeni** [comment]
This issue should be solved from the plugin it self no ? because the same issue doesnt happen with other plugins that im using

**Comment by DaveMBush** [comment]
@Oussemasahbeni 1.0.10 should fix it.  Let me know if it does not.

**Comment by Oussemasahbeni** [comment]
Problem fixed , thank you for your time

**Comment by DaveMBush** [comment]
This fix broke everything for everyone else.  While fixing that, I also tried to keep this fix but since I don't have a repo, I was not able to test.

Could you try version 1.0.11 and let me know if it is still fixed or not.  OR you can send me a repo and I can check for myself.

**Comment by Oussemasahbeni** [comment]
I switch to the .js instead of .mjs , "@smarttools/eslint-plugin-rxjs": "1.0.11" works fine for me with commonJs format , the .mjs is still not working tho

**Comment by DaveMBush** [comment]
This is finally fixed, and verified in 1.0.15
